config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :accommodations, controller: :properties, only: [:index, :show]

  PagesController.action_methods.each do |action|
    get "/#{action}".dasherize, to: "pages##{action}", as: "#{action}_page"
  end

  post "/contact/thank-you".dasherize, to: "pages#contact_thank_you", as: "post_contact_thank_you_page"
  post "/owners/thank-you".dasherize, to: "pages#owners_thank_you", as: "post_owners_thank_you_page"

  namespace :api do
    resources :units, only: [:index, :show] do
      resources :stays, only: [:get]
    end
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  DATE_FORMAT = '%m/%d/%Y'.freeze

  def index
    @area       = params[:area] || '-'
    @start_date = params[:start_date]
    @end_date   = params[:end_date]
    @guests     = params[:guests]
    @sort       = params[:sort] || 'P'
    search_hash = { area: params[:area], start_date: params[:start_date], end_date: params[:end_date], guests: params[:guests], sort: params[:sort], room: params[:room] }
    searcher = PropertyRetriever.new search_hash
    units = searcher.retrieve
    @units = WillPaginate::Collection.create((params[:page] || 1).to_i, 10, units.count) do |pager|
      pager.replace(units[pager.offset, pager.per_page].to_a)
    end
  end

  def show
    @id                = params[:id]
    @booking_id        = params[:id].to_str.split('-', 2).last
    @unit              = UnitRepository.get(@id)
    @property_title    = @unit.name
    @property_subtitle = @unit.address[:street]
    @amenities         = @unit.available_amenities
    @guests            = params[:guests] || 1
    @guest_amount_list = (1..@unit.occupancy).map { |v| v }
    @start_date        = !params[:start_date].blank? ? params[:start_date] : Date.today.strftime(DATE_FORMAT)
    @end_date          = !params[:end_date].blank? ? params[:end_date] : (Date.today + 7).strftime(DATE_FORMAT)
    @random_units      = UnitRepository.random_units(limit: 3, except: [@id])

    lookup_rates if [:start_date, :end_date, :guests].all? { |k| params.key?(k) && !params[k].blank? }
    get_images
  end

  private

  def lookup_rates
    @lookup         = true
    @available      = true
    start_date      = Date.strptime(@start_date, DATE_FORMAT)
    end_date        = Date.strptime(@end_date, DATE_FORMAT)
    @length_of_stay = end_date.mjd - start_date.mjd
    @guests         = @guests == "all" ? 1 : @guests

    @rates = Stay.lookup(@id,
                        start_date: start_date,
                        end_date: end_date,
                        guests: @guests)

    @nightly_rate      = '%.2f' % (@rates.base_amount / @length_of_stay)
    @base_amount       = '%.2f' % @rates.base_amount
    @tax_amount        = '%.2f' % @rates.taxes[0].amount
    @fees              = @rates.fees
    @total_amount      = '%.2f' % @rates.total_amount
  rescue Stay::Unavailable
    @available = false
  end

  def get_images
    @videos = @unit.videos
    @standard_images = @unit.standard_images
    @large_images = @unit.large_images
  end

end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_rate_panel.html.erb
<aside class="request-booking md-one-third">
<%- if @lookup && @available %>
    <header class="booking-header hacienda-bg-color">
        <h2>$<%= '%.0f' % @nightly_rate %> <span class="term">Per Night</span></h2>
    </header>
    <%= form_tag("/accommodations/#{@id}", {method: 'get', class: 'gw no-gutter booking-details'}) do %>
    <table>
        <tr class="date-select">
            <td class="g sm-three-eighths">
                <label for="start_date">Arrive</label>
                <%= text_field_tag "start_date", @start_date, class: 'no-borders datepicker', placeholder: 'mm/dd/yyyy' ,readonly: 'readonly'%>
            </td>
            <td class="g sm-three-eighths">
                <label for="end_date">Depart</label>
                <%= text_field_tag "end_date", @end_date, class: 'no-borders datepicker', placeholder: 'mm/dd/yyyy', readonly: 'readonly'%>
            </td>
            <td class="g sm-two-eighths">
                <label for="guests">Guests</label>
                <div class="select-style">
                <%= select_tag "guests", options_for_select(@guest_amount_list, @guests), class:'rate-panel-guest-height' %>
                </div>
            </td>
        </tr>
        <tr class="full-width-container">
            <td>
                <input class="btn no-min-width hacienda-bg-color" type="submit" value="Search Again">
            </td>
        </tr>
        <tr class="details first">
            <td class="g two-thirds">$<%=  '%.0f' % @nightly_rate %> x <%= @length_of_stay %> nights</td>
            <td class="g one-third text-align-right">$<%= @base_amount %></td>
        </tr>
        <tr class="details">
            <td class="g two-thirds">Tax</td>
            <td class="g one-third text-align-right">$<%= @tax_amount %></td>
        </tr>
        <% @fees.each do |fee| %>
        <tr class="details">
            <td class="g two-thirds"><%= fee.name %></td>
            <td class="g one-third text-align-right">$<%= '%.2f' % fee.amount %></td>
        </tr>
        <% end %>
        <tr class="details">
            <td class="g two-thirds highlight">Total</td>
            <td class="g one-third highlight text-align-right">$<%= '%.2f' % @total_amount %></td>
        </tr>
        <tr class="details">
            <td class="g two-thirds"><a href="/trip-cancellation-insurance" target="_blank">Optional Trip Cancellation Insurance</a></td>
            <td class="g one-third text-align-right">$<%= '%.2f' % ((@base_amount.to_f * 1.12) * 0.065) %></td>
        </tr>
        <tr class="details">
            <td class="g two-thirds highlight">Total w/ Insurance</td>
            <td class="g one-third highlight text-align-right">$<%= '%.2f' % (((@base_amount.to_f * 1.12) * 0.065) + @total_amount.to_f) %></td>
        </tr>
        <tr class="full-width-container">
            <td>
                <a href="http://bookings.oceano-rentals.com/Booking/RateDetails/<%= @booking_id %>?arrive=<%= @start_date %>&depart=<%= @end_date %>&adults=<%= @guests %>" class="btn request-booking-link hacienda-bg-color">Request Booking</a>
            </td>
        </tr>
        <tr class="full-width-container">
            <td>
                <span class="note">The total above is an estimate and includes rent, taxes, and additional fees.</span>
            </td>
        </tr>
    </table>
    <% end %>
<%- elsif @lookup && !@available %>
    <header class="booking-header hacienda-bg-color">
        <h2>Availability and Rate</h2>
    </header>
    <%= form_tag("/accommodations/#{@id}", {method: 'get', class: 'gw no-gutter booking-details'}) do %>
    <table>
        <tr class="date-select">
        <td class="g sm-three-eighths">
            <label for="start_date">Arrive</label>
            <%= text_field_tag "start_date", @start_date, class: 'no-borders datepicker', placeholder: 'mm/dd/yyyy', readonly: 'readonly'%>
        </td>
        <td class="g sm-three-eighths">
            <label for="end_date">Depart</label>
            <%= text_field_tag "end_date", @end_date, class: 'no-borders datepicker', placeholder: 'mm/dd/yyyy', readonly: 'readonly' %>
        </td>
        <td class="g sm-two-eighths">
            <label for="guests">Guests</label>
            <div class="select-style">
            <%= select_tag "guests", options_for_select(@guest_amount_list, @guests), class:'rate-panel-guest-height' %>
            </div>
        </td>
        </tr>
        <tr class="full-width-container">
            <td class="g">This property is unavailable for the chosen dates.</td>
        </tr>
        <tr class="full-width-container">
        <td>
            <input class="btn no-min-width hacienda-bg-color" type="submit" value="Check Availability">
        </td>
        </tr>
    </table>
    <% end %>
<%- else %>
    <header class="booking-header hacienda-bg-color">
        <h2>Availability and Rate</h2>
    </header>
    <%= form_tag("/accommodations/#{@id}", { method: 'get', class: 'gw no-gutter booking-details' }) do %>
    <table>
        <tr class="date-select">
        <td class="g sm-three-eighths">
            <label for="start_date">Arrive</label>
            <%= text_field_tag "start_date", @start_date, class: 'no-borders datepicker', placeholder: 'mm/dd/yyyy', readonly: 'readonly' %>
        </td>
        <td class="g sm-three-eighths">
            <label for="end_date">Depart</label>
            <%= text_field_tag "end_date", @end_date, class: 'no-borders datepicker', placeholder: 'mm/dd/yyyy', readonly: 'readonly'%>
        </td>
        <td class="g sm-two-eighths">
            <label for="guests">Guests</label>
            <div class="select-style">
            <%= select_tag "guests", options_for_select(@guest_amount_list, @guests), class:'rate-panel-guest-height' %>
            </div>
        </td>
        </tr>
        <tr class="full-width-container">
            <td class="g">Check availablilty to view rates and fees.</td>
        </tr>
        <tr class="full-width-container">
        <td>
            <input class="btn no-min-width hacienda-bg-color" type="submit" value="Check Availability">
        </td>
        </tr>
    </table>
    <% end %>
<% end %>
</aside>
<style>
  .hacienda-bg-color{
    background-color: #d0aa69 !important;
  }
</style>

app/views/properties/_search_form.html.erb
<%= form_tag(accommodations_path, class: 'gw no-gutter', method: :get) do %>
    <fieldset class="g sm-one-whole md-five-twelfths">
        <label class="is-visually-hidden">Rooms</label>
        <div class="select-style">
          <%- areas_options = [['Rooms', '-', {disabled: 'disabled'}], ['Any', 'all']] + rooms %>
          <%= select_tag "room", options_for_select(areas_options, area), id: 'select-drop' %>
        </div>
    </fieldset>
    <fieldset class="g sm-one-third md-one-seventh">
      <%= text_field_tag "start_date", start_date, class: 'no-borders datepicker', placeholder: 'Arrive' %>
    </fieldset>
    <fieldset class="g sm-one-third md-one-seventh">
      <%= text_field_tag "end_date", end_date, class: 'no-borders datepicker', placeholder: 'Depart' %>
    </fieldset>
    <% if local_assigns[:home_search] %>
      <fieldset class="g sm-one-fourth md-one-eighth text-align-right">
          <label class="is-visually-hidden" for="guests">Guests</label>
          <div class="select-style">
              <select name="guests" id="guests">
                  <option disabled selected>Guests</option>
                  <option value="all">Any</option>
                  <option value="1">1</option>
                  <option value="2">2</option>
                  <option value="3">3</option>
                  <option value="4">4</option>
                  <option value="5">5</option>
                  <option value="6">6</option>
                  <option value="7">7</option>
                  <option value="8">8</option>
                  <option value="9">9</option>
                  <option value="10">10</option>
              </select>
          </div>
      </fieldset>
    <% else %>
      <fieldset class="g sm-one-fourth md-one-eighth text-align-right">
          <label class="is-visually-hidden" for="guests">Guests</label>
          <div class="select-style">
            <%- sort_options = [['Sort by', '-', {disabled: 'disabled'}]] + sort_by %>
            <%= select_tag "sort", options_for_select(sort_options, sort) %>
          </div>
      </fieldset>
    <% end %>
    <footer class="g md-two-twelfths">
      <input class="btn btn--brown no-min-width max-width search-btn" type="submit" value="Search">
    </footer>
<% end %>

app/views/properties/index.html.erb
<% content_for :hero_title, "Find a Rental".html_safe %> <!-- Hero/Page Title -->
<% content_for :lede, "Search for a rental at Rocky Point".html_safe %>
<section class="padded-top scallop-top beige-bg">
    <div class="layout-container">
        <div class="property-search">
          <%= render partial: 'search_form', locals: { area: @area, start_date: @start_date, end_date: @end_date, sort: @sort } %>
        </div>
    </div>
    <%- if @units.empty? %>
    <div class="layout-container-smaller padded-bottom layout-centered">
        <h1>No available rental properties found</h1>
        <p>Please adjust your search and try again.</p>
    </div>
    <%- else %>
    <div class="layout-container">
        <ul class="properties-list gw small-gutter">
            <%- @units.each do |unit| %>
            <li class="property g sm-one-half md-one-whole">

                <%
                full_link = accommodation_url(unit.code) + "?start_date=#{@start_date}&end_date=#{@end_date}&guests=#{@guests}"
                %>

                <a href="<%= full_link %>"><img class="property-thumb" src="<%= unit.standard_images[0][:url] %>"></a>
                <div class="details">
                    <div class="gw small-gutter">
                        <div class="g md-three-eighths">
                            <h2><a href="<%= full_link %>"><%= unit.name %></a></h2>
                            <p class="location"><%= unit.address.street %> <br><%= unit.address.city %>, <%= unit.address.country %></p>
                        </div>
                        <div class="g md-three-eighths">
                            <ul class="offerings">
                                <li>
                                    <i class="icon icon-bath"></i>
                                    <span class="detail"><%= unit.bathrooms %> bath</span>
                                </li>
                                <li>
                                    <i class="icon icon-bed"></i>
                                    <span class="detail"><%= unit.bedrooms %> beds</span>
                                </li>
                                <li>
                                    <i class="icon icon-guests"></i>
                                    <span class="detail"><%= unit.occupancy %> guests</span>
                                </li>
                            </ul>
                        </div>
                        <div class="g md-two-eighths">
                            <span class="price"></span>
                            <span class="type"><%= unit.type %></span>
                        </div>
                    </div>
                </div>
            </li>
            <%- end %>

        </ul>
        <div class="pagination pagination-centered">
        <%= will_paginate @units, previous_label: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16.3 32.6"><polygon points="16.3,32.6 0,16.3 16.3,0"/></svg>',
                                  next_label: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16.3 32.6"><polygon points="0,0 16.3,16.3 0,32.6"/></svg>' %>
        <%- end %>
        </div>
    </div>
</section>

app/views/properties/show.html.erb
<script type="text/javascript" src="//maps.googleapis.com/maps/api/js?sensor=false"></script>

<% content_for :hero_title, @property_title.html_safe %>
<% content_for :lede, @property_subtitle.html_safe %>

<section class="scallop-top">
  <div class="layout-container">
    <div class="md-two-thirds">
      <ul class="offerings">
        <li>
          <i class="icon icon-bath"></i>
          <span class="detail"><%= @unit.bathrooms %> Bath</span>
        </li>
        <li>
          <i class="icon icon-bed"></i>
          <span class="detail"><%= @unit.bedrooms %> Beds</span>
        </li>
        <li>
          <i class="icon icon-guests"></i>
          <span class="detail"><%= @unit.occupancy %> Guests</span>
        </li>
        <li>
          <i class="icon icon-apartment"></i>
          <span class="detail"><%= @unit.type.capitalize %></span>
        </li>
      </ul>
    </div>
  </div>
</section>

<section class="padded-top padded-bottom beige-bg">
  <div class="layout-container">
    <%= render 'rate_panel' %>

    <div class="property-details md-two-thirds">

      <div class="image-grouping" id="image-lightbox">
        <div class="row">
        <%- if @large_images.count > 0 %>
          <article class="one-whole md-two-thirds tile">
            <a rel="image-gallery" href="<%= @large_images[0][:url] %>" title="<%= @large_images[0][:title] %>" class="fancybox contain" style="background-image: url('<%= @standard_images[0][:url] %>');"></a>
          </article>
        <%- end %>
        <%- if @large_images.count > 1 %>
          <article class="one-whole md-one-third tile">
            <a rel="image-gallery" href="<%= @large_images[1][:url] %>" title="<%= @large_images[1][:title] %>" class="fancybox contain" style="background-image: url('<%= @standard_images[1][:url] %>');"></a>
          </article>
        <%- end %>
        </div>
        <div class="row">
        <%- if @large_images.count > 2 %>
          <article class="one-whole md-one-third tile">
            <a rel="image-gallery" href="<%= @large_images[2][:url] %>" title="<%= @large_images[2][:title] %>" class="fancybox contain" style="background-image: url('<%= @standard_images[2][:url] %>');"></a>
          </article>
        <%- end %>
        <%- if @large_images.count > 3 %>
          <article class="one-whole md-one-third tile">
            <a rel="image-gallery" href="<%= @large_images[3][:url] %>" title="<%= @large_images[3][:title] %>" class="fancybox contain" style="background-image: url('<%= @standard_images[3][:url] %>');"></a>
          </article>
        <%- end %>

          <% for i in 5..@standard_images.count do %>
            <a rel="image-gallery" href="<%= @large_images[i-1][:url] %>" title="<%= @large_images[i-1][:title] %>" class="fancybox hidden"></a>
          <% end %>

          <article class="one-whole md-one-third tile">
            <a href="#" class="contain black placehold-all-images open-lightbox">
              <div class="over">
                <h2>See All <%= @standard_images.count %> Photos</h2>
              </div>
            </a>
          </article>
        </div>
      </div>

      <div class="gw">
        <div class="g">
          <%
            unless @videos.empty? || @videos[0][:formats][:url].empty?
              url = @videos[0][:formats][:url]
          %>

          <p><a class="fancybox-media btn video-tour-btn hacienda-bg-color" title="Video Tour" href="<%= url %>" target="_blank">View a video tour</a></p>
          <% end %>
        </div>
      </div>


      <div class="gw">
        <div class="g md-one-fourth">
          <h2 class="heading-two">Description</h2>
        </div>
        <div class="g md-three-fourths">
          <p><%= @unit.descriptions[:text][0][:description] %></p>
        </div>
      </div>

      <hr>

      <div class="gw">
        <div class="g md-one-fourth">
          <h2 class="heading-two">Property Details</h2>
        </div>
        <div class="g md-three-fourths">
          <ul class="gw no-gutter no-padding">
            <li class="g md-one-half padded-right"><p><b>Property Type:</b> <%= @unit.type.capitalize %></p></li>
            <li class="g md-one-half padded-right"><p><b>Bedrooms:</b> <%= @unit.bedrooms %></p></li>
            <li class="g md-one-half padded-right"><p><b>Bathrooms:</b> <%= @unit.bathrooms %></p></li>
            <li class="g md-one-half padded-right"><p><b>Floors:</b> <%= @unit.num_floors %></p></li>
            <li class="g md-one-half padded-right"><p><b>Occupancy:</b> <%= @unit.occupancy %></p></li>
          </ul>
        </div>
      </div>

      <hr>
      <div class="gw">
        <div class="g md-one-fourth">
          <h2 class="heading-two">Amenities</h2>
        </div>
        <div class="g md-three-fourths">
          <ul class="gw no-gutter no-padding">
            <% @amenities.each do |amenity| %>
            <li class="g md-one-half padded-right"><p><%= amenity.to_s.titleize %></p></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>

<%- @unit.reviews.sample(3).compact.tap do |reviews| %>
<%- break if reviews.empty? %>
<section class="padded-top padded-bottom">
  <div class="layout-container">
    <div class="md-two-thirds">
      <h2 class="heading-two bottom-spacing-large">Testimonies</h2>
      <ul class="testimonials testimonials-paginated normal gw large-gutter">
        <%- reviews.each do |review| %>
        <li class="g sm-one-whole">
          <blockquote>
            <p class="persons-words">“<%= review[:comment].html_safe %></p>
            <%- unless review[:city].empty? || review[:state].empty? %>
            <span class="persons-name"><%= review[:city] %>, <%= review[:state] %></span>
            <% end %>
          </blockquote>
        </li>
        <%- end %>
      </ul>
    </div>
  </div>
</section>
<%- end %>

<script src='https://maps.googleapis.com/maps/api/js?v=3.exp'></script><div style='overflow:hidden;height:340px;width:100%;'><div id='gmap_canvas' style='height:340px;width:100%;'></div><div><small><a href="http://embedgooglemaps.com">									embed google maps							</a></small></div><div><small><a href="https://privacypolicytemplate.net">privacy policy template</a></small></div><style>#gmap_canvas img{max-width:none!important;background:none!important}</style></div><script type='text/javascript'>function init_map(){var myOptions = {zoom:10,center:new google.maps.LatLng(31.3268218,-113.5311843),mapTypeId: google.maps.MapTypeId.ROADMAP};map = new google.maps.Map(document.getElementById('gmap_canvas'), myOptions);marker = new google.maps.Marker({map: map,position: new google.maps.LatLng(31.3268218,-113.5311843)});infowindow = new google.maps.InfoWindow({content:'<strong>Hacienda del Mar</strong><br>Puerto Peñasco Sonora, Mexico<br>'});google.maps.event.addListener(marker, 'click', function(){infowindow.open(map,marker);});infowindow.open(map,marker);}google.maps.event.addDomListener(window, 'load', init_map);</script>

<style>
  .hacienda-bg-color{
    background-color: #d0aa69 !important;
  }
</style>